### ISSUE TITLE
Some missing details to train the models

### ISSUE THREAD

**Issue by a64bit** [aliprf/ACR-Loss#3]
Hello, Thank you for sharing the code of this project. 

I am trying to train your model, but there are some missing details as follows:
   1. In the README file in the [Preparing Data section](https://github.com/aliprf/ACR-Loss#preparing-data) you say `Data needs to be normalized and saved in npy format.` .. So what kind of normalization is needed here? Is it the same normalization used in the function [_load_and_normalize](https://github.com/aliprf/ACR-Loss/blob/2ef8440b7ffd3c1aaeb80fd6d29c89c1bfe498a2/train.py#L208)? It will be very helpful if you can share the scripts you used to do this normalization for the datasets you used.
   
   2. When saving and loading the PCA files, I noticed you use the [pca_percentage](https://github.com/aliprf/ACR-Loss/blob/main/pca_utilities.py#L40) in the name of the saved npy files. So, should I create a npy file for each PCA percentage that is used while training [[80, 85, 90, 95]](https://github.com/aliprf/ACR-Loss/blob/main/train.py#L140)? 
   
 Thank you.

**Comment by aliprf** [comment]
Hi. Sorry for my late reply. 

1- I used zero mean normalization. The original landmark points are between 0 to 224, so, after normalization, we have all the landmark points to be in [-0.5, +0.5]. you can use the [_load_and_normalize](https://github.com/aliprf/ACR-Loss/blob/2ef8440b7ffd3c1aaeb80fd6d29c89c1bfe498a2/train.py#L208) for that purpose.

2- Yes, you are right.

please let me know in case more information is needed.
