### ISSUE TITLE
Has this article been published, and should I still cite the preprint form?

### ISSUE THREAD

**Issue by tianmaxingkong12** [aliprf/ACR-Loss#4]

**Comment by aliprf** [comment]
Yes.
 ACR Loss: Adaptive Coordinate-Based Regression Loss for Face Alignment is accepted, and presented at 26th International Conference on Pattern Recognition (ICPR2022). 
Please cite the pre-print version till the conference publish the proceeding.

**Comment by aliprf** [comment]
https://ieeexplore.ieee.org/document/9956683
